### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by ChrisDelClea** [gamcoh/st-card#1]
Hey @gamcoh ,

can you update your package to make it compatible with Python Version > 3.7.8?

Best regards
Chris

**Comment by gamcoh** [comment]
Hi @ChrisDelClea 

Did you close the issue because it is already compatible?
I have not tested on this python version yet

**Comment by ChrisDelClea** [comment]
Just closed as i found that i downloaded the wrong card component and the error was on my end. Thanks for askin, @gamcoh.
