### ISSUE TITLE
Need some customization

### ISSUE THREAD

**Issue by fatmagamalgalal** [gamcoh/st-card#13]
I need to customize font size, font family and multi line description. As well as the card width and height.

**Comment by gamcoh** [comment]
what are you thinking of when you're saying multi line description?
Something like that?
```py
card(
  text=["First line", "second line"])
```

**Comment by fatmagamalgalal** [comment]
or 'First line\nsecond line" will also be fine.

**Comment by gamcoh** [comment]
I'm afraid that parsing user input on the fly might bring too much dark magic, so maybe a list is better

**Comment by fatmagamalgalal** [comment]
ok, no problem, but the size of the card and the style of the font is too essential to use the cards.

**Comment by gamcoh** [comment]
Yep, I'll try to tackle this issue in the coming days

**Comment by gamcoh** [comment]
It's done with the last 2 commits
