### ISSUE TITLE
TypeError: card() got an unexpected keyword argument 'on_click'

### ISSUE THREAD

**Issue by C45513-L** [gamcoh/st-card#14]
TypeError: card() got an unexpected keyword argument 'on_click' 
TypeError: card() got an unexpected keyword argument 'styles' 

Hi, both errors found with version 0.0.61.

**Comment by gamcoh** [comment]
Could you share how you're calling the component? It works on my setup

**Comment by jung-hunsoo** [comment]
I had the same error, and solved by passing `on_click=lambda: None`.
