### ISSUE TITLE
Frontend build folder missing

### ISSUE THREAD

**Issue by marcjulianschwarz** [gamcoh/st-card#15]
Hi,

it seems like the frontend build folder is missing when installing with pip. Running a streamlit app with card components throws this error:
```
FileNotFoundError: [Errno 2] No such file or directory: ...\\.conda\\envs\\...\\Lib\\site-packages\\streamlit_card\\frontend\\build\\null'
ComponentRequestHandler: GET ...\.conda\envs\...\Lib\site-packages\streamlit_card\frontend\build\null read error
```

I once had a similar issue with [this streamlit component (issue)](https://github.com/giswqs/streamlit-timeline/issues/59).

**Comment by gamcoh** [comment]
Hi, I just installed it on a new instance, it works well.

Could you share us your environment config?

Also you link is 404

**Comment by marcjulianschwarz** [comment]
Oops, sorry about the link. Here it is: https://github.com/giswqs/streamlit-timeline/issues/5

**Comment by marcjulianschwarz** [comment]
I am running python 3.10.12 with streamlit version 1.25.0 and streamlit-card version 0.0.61.

**Comment by OJddJO** [comment]
Did you install it with `pip install streamlit-card` or download the release file ?

**Comment by marcjulianschwarz** [comment]
I used `pip install streamlit-card`

**Comment by OJddJO** [comment]
Try to use this then [streamlit_card.zip](https://github.com/gamcoh/st-card/files/12590166/streamlit_card.zip) (Original one)

Or this [streamlit_card.zip](https://github.com/gamcoh/st-card/files/12590023/streamlit_card.zip).
It's a version that I modified and compiled myself.
It has the same properties and arguments as the normal one + some usefull things like the ability to modify the CSS of every element.

Put the folder at the root of your project and do this to import it with
``` py
from streamlit_card import Card
```

**Comment by OJddJO** [comment]
If you want the normal one: [st-card.zip](https://github.com/gamcoh/st-card/files/12590098/st-card.zip)
