### ISSUE TITLE
Click on multiple cards

### ISSUE THREAD

**Issue by Haaaaaaaaaland** [gamcoh/st-card#17]
Hello,

Thank you for providing the card feature!

When using multiple cards, how can I get click results for each card?
For instance, with the following code:

```python
hasClicked1 = card(
    title="111",
    text="Some description",
    image="http://placekitten.com/200/300",
    key="111",
    on_click=lambda: print("111"),
)
hasClicked2 = card(
    title="222",
    text="Some description",
    image="http://placekitten.com/200/300",
    key="222",
    on_click=lambda: print("222"),
)
print(f"{hasClicked1} {hasClicked2}")
```

When 111 is clicked, the result is:
```python
True False  # print
```

And click 222, the result is:
```python
True True  # print ...?
```

Since I only clicked on the "222" card,
I hoped that **"False True"** would come out, but it didn't work as expected.

How can i fix it?

Thank you in advance for your response!

**Comment by OJddJO** [comment]
Try using `experimental_rerun()`
``` python
if hasClicked1 or hasClicked2:
    st.experimental_rerun()
```
Something like that, since the state of cards are persistent.

**Comment by gamcoh** [comment]
@Haaaaaaaaaland is your issue solved?
