### ISSUE TITLE
Can card add a settings: use_column_width=True ?

### ISSUE THREAD

**Issue by jourmore** [gamcoh/st-card#19]
Can card add a settings: use_column_width=True ?
If this can be added, it will be more useful ！

**Comment by OJddJO** [comment]
Did a pull request (https://github.com/gamcoh/st-card/pull/20) for it

**Comment by jourmore** [comment]
> Did a pull request (#20) for it

Thank you ！！！

**Comment by gamcoh** [comment]
merged
