### ISSUE TITLE
Can't update title CSS styling

### ISSUE THREAD

**Issue by remolloy1010** [gamcoh/st-card#23]
The package documentation says the "title" is also CSS editable but when I try to edit, nothing happens. 

The following example works for "text" but updates all the text in the card. 
```
from streamlit_card import card

res = card(
    title="Streamlit Card",
    text="This is a test card",
    image="https://placekitten.com/500/500",
    styles={
        "card": {
            "width": "500px",
            "height": "500px",
            "border-radius": "60px",
            "box-shadow": "0 0 10px rgba(0,0,0,0.5)",
            
        },
        "text" : {
            "color" : "red"
        }
    }
)
```
![image](https://github.com/gamcoh/st-card/assets/35467838/d94d7e88-ac3f-4264-8452-8ac5acf66ce0)

When I try to update "text" to title, the font color is white and nothing changes.
```
from streamlit_card import card

res = card(
    title="Streamlit Card",
    text="This is a test card",
    image="https://placekitten.com/500/500",
    styles={
        "card": {
            "width": "500px",
            "height": "500px",
            "border-radius": "60px",
            "box-shadow": "0 0 10px rgba(0,0,0,0.5)",
            
        },
        "title" : {
            "color" : "red"
        }
    }
)
```
![image](https://github.com/gamcoh/st-card/assets/35467838/d969408f-dbb1-4ed4-8578-94143ad551bc)

I'm using streamlit-card==0.0.61 and Python 3.9.13. 

Any ideas why?

**Comment by gamcoh** [comment]
You're right it was an issue, should work fine now with the latest version v1.0.0

`pip install streamlit-card --upgrade`
