### ISSUE TITLE
How can we access the hover property on the card created? 

### ISSUE THREAD

**Issue by adityanair97** [gamcoh/st-card#26]
Trying to access the hover property of the card to show the URL that it'd would redirect to. Is that possible in the styles dict itself?

**Comment by OJddJO** [comment]
Nope

**Comment by adityanair97** [comment]
Any sort of workaround that you think might work out ? Or can something be implemented by default: if a url is specified, show it while hovering over the card.

**Comment by OJddJO** [comment]
I think that can be implemented.

**Comment by gamcoh** [comment]
@OJddJO are you on it?

**Comment by OJddJO** [comment]
> @OJddJO are you on it?

No, I was thinking a way to do it but I don't have enough time

**Comment by adchalmers** [comment]
For anyone else that is interested, hover properties can be accessed via:

```
card_style = {
    "card": {
        <CARD PROPS>,
        "&:hover": {
            <HOVER PROPS>
        }
    }
}

**Comment by zimmer44** [comment]
Any update on this feature would really like to create a tooltip when hovering over one of the cards.

Thanks for all the work on the package super useful.

**Comment by gamcoh** [comment]
Hi everyone I don't think implementing the hover of the card for a tooltip is something we should be focusing on, if you want to stylize the card when the hover effect is on, this is the right way:



> For anyone else that is interested, hover properties can be accessed via:
> 
> ```
> card_style = {
>     "card": {
>         <CARD PROPS>,
>         "&:hover": {
>             <HOVER PROPS>
>         }
>     }
> }
> ```
