### ISSUE TITLE
Excessive Padding Around Card

### ISSUE THREAD

**Issue by maxdiegoduron** [gamcoh/st-card#32]
The padding around the outside of the card is excessive. Can we make this a part of the function kwargs?

**Comment by OJddJO** [comment]
You can change the padding using CSS
``` py
from streamlit_card import card

res = card(
    title="Streamlit Card",
    text="This is a test card",
    image="https://placekitten.com/500/500",
    styles={
        "div": {
            "padding": "5px",
            ...
        }
    }
)
```
Something like this

**Comment by maxdiegoduron** [comment]
But even by doing this I still cant get rid of the unnecessary space top
and bottom of the card

    streamlit_card.card(title="You have selecteds ",
                        text=f"{len(wells_selected)} wells",
                        image="
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJyPdNzgSGLTJmpJgCJSVFnmcPd9VMX40E3A&s
",
                        styles={
                            "card": {
                                "width": "250px",
                                "height": "100px",
                                "border-radius": "6px",
                                "padding": "0px 0px 0px 0px",
                                "box-shadow": "0 0 10px rgba(0,0,0,0.5)",
                            },
                            "div": {"padding": "0px 10px 10px 0px"},
                            "title": {"padding": "0px 0px 0px 0px",
                                      "font-size": "20px"},
                            "text": {"font-size": "22px"}
                        },

                        )

[image: image.png]

**Comment by OJddJO** [comment]
set the padding option in the div CSS to 0

**Comment by maxdiegoduron** [comment]
Can you send small example please with 2 card stacked on top of each other ?

**Comment by OJddJO** [comment]
![image](https://github.com/gamcoh/st-card/assets/95376647/01435ced-55e4-4508-a96d-76355d7e8778)
This is the minimum space between two cards. You cannot change that, I think it's due to streamlit itself.
Look:
![image](https://github.com/gamcoh/st-card/assets/95376647/33c4a05d-2dcf-4e82-b02b-742014725ba9)

```py
card(
    title="Streamlit Card",
    text="This is a test card",
    image="http://placekitten.com/200/300",
    key="card1",
    styles={
        "card": {
            "width": "500px",
            "height": "500px",
            "padding": "0px",
            "margin": "0px"
        },
        "div": {
            "padding": "0px"
        }
    }
)

card(
    title="Streamlit Card",
    text="This is a test card",
    image="http://placekitten.com/200/300",
    key="card2",
    styles={
        "card": {
            "width": "500px",
            "height": "500px",
            "padding": "0px",
            "margin": "0px"
        },
        "div": {
            "padding": "0px"
        }
    }
)```

**Comment by maxdiegoduron** [comment]
Perfect!!! you are awesome the Margin was the issue!!! Thank you so much for sharing!!!
