### ISSUE TITLE
how could i config my nginx 

### ISSUE THREAD

**Issue by HakunamatataLeo** [gamcoh/st-card#34]
![image](https://github.com/gamcoh/st-card/assets/4550421/3c241f4c-36a6-4170-9750-0f16e76442a2)

my nginx.conf

    server {
        listen       8000;
        server_name  localhost;

       location = /hsk {
             proxy_pass http://127.0.0.1:8501;
        }

        location ^~ /static {
            proxy_pass http://127.0.0.1:8501/static/;
        }

        location = /_stcore/health {
            proxy_pass http://127.0.0.1:8501/_stcore/health;
        }

      location = /_stcore/host-config {
            proxy_pass http://127.0.0.1:8501/_stcore/host-config;
        }

        location = /hsk/_stcore/health {
            proxy_pass http://127.0.0.1:8501/_stcore/health;
        }

        location = /hsk/_stcore/host-config {
            proxy_pass http://127.0.0.1:8501/_stcore/host-config;
        }

        location = /_stcore/allowed-message-origins {
            proxy_pass http://127.0.0.1:8501/_stcore/allowed-message-origins;
        }

        location = /hsk/_stcore/stream {
            proxy_pass http://127.0.0.1:8501/_stcore/stream;
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
 add_header Content-Security-Policy "default-src 'self' https: data: 'unsafe-inline';" always;

@gamcoh pls

**Comment by gamcoh** [comment]
I don't think your issue is with nginx, could you share your code please?
