### ISSUE TITLE
Multi-line text

### ISSUE THREAD

**Issue by blacksmithop** [gamcoh/st-card#35]
Is there anyway for me to have multi-line text inside a card? The `\n` seem to be getting ignored

![image](https://github.com/gamcoh/st-card/assets/60320192/c3d023af-2bf4-46fd-b6d5-8c17819413e5)

**Comment by gamcoh** [comment]
In the README you can see:
```py
from streamlit_card import card

res = card(
    title="Streamlit Card",
    text=["This is a test card", "This is a subtext"],
    image="https://placekitten.com/500/500",
)
```

you can use a list of texts
