### ISSUE TITLE
How to customize space around card?

### ISSUE THREAD

**Issue by YojanaGadiya** [gamcoh/st-card#40]
Dear @gamcoh ,

I am wondering if there is a way to customize the space around the card using CSS. If yes, please could you let me know the best way to do it?

Regards,
Yojana Gadiya

**Comment by gamcoh** [comment]
Hi, you could use margins like so:

```py
from streamlit_card import card

res = card(
    title="Streamlit Card",
    text="This is a test card",
    image="https://placekitten.com/500/500",
    styles={
        "card": {
            "margin": "40px", <-- margin around the card
            ...
        },
        ...
    }
)
```

Learn more [here](https://developer.mozilla.org/en-US/docs/Web/CSS/margin)
