### ISSUE TITLE
Which type of image can I use for "image" attribute?

### ISSUE THREAD

**Issue by johnnyb1509** [gamcoh/st-card#7]
Hi authors,

I'm using your package but cannot change any local image instead of your's example. Specifically, I have tried read some type of image such as .jpg and .png by using PIL.Image, but then it shows an error of cannot serialize as bellow

```
MarshallComponentException: ('Could not convert component args to JSON', TypeError('Object of type PngImageFile is not JSON serializable'))

```

How can I fix this

**Comment by gamcoh** [comment]
Hi there, I think this is a duplicate of this #5

**Comment by johnnyb1509** [comment]
> Hi there, I think this is a duplicate of this #5

Yes, thank you so much!
